import { FaCheckCircle, FaComments, FaCut, FaHandSparkles, FaHands, FaGem, FaPaintBrush, FaGlobeAmericas } from "react-icons/fa"
// import { dataTodoList } from '../constants/dataTodoList'
// import { dataMessenger } from '../constants/dataMessenger'

export const portfolioItems = [
	{
		id: 1,
		title: "ToDo List Fullstack",
		description: "Приложение для управления задачами с регистрацией, аутентификацией через JWT и SQLite базой данных",
		icon: <FaCheckCircle />,
		tech: ["ReactJS", "JWT", "Express", "SQLite3", "Tailwindcss", "Render.com"],
		featured: true,
		demo: "https://todo-react-node-sqlite-jwt.onrender.com/register",
		// link: dataTodoList
		image: "/images/todolist.jpg", 
	},
	{
		id: 2,
		title: "Мессенджер Real-time",
		description: "Чат-приложение с комментами, загрузкой файлов",
		icon: <FaComments />,
		tech: ["ReactJS", "Node.js", "PostgreSQL", "Vercel"],
		featured: true,
		demo: "https://messenger-full.vercel.app/",
		// link: dataMessenger
		image: "/images/messenger.jpg",
	},
	{
		id: 3,
		title: "Тестовое задание - верстка",
		description: "Верстка и доработка существующего сайта с адаптивным дизайном",
		icon: <FaComments />,
		tech: ["ReactJS", "jQuery", "Bootstrap4", "Vite"],
		demo: "https://petersburg-time-course.vercel.app/#about-course",
		image: "/images/peterburg-course.jpg",
	},
	{
		id: 4,
		title: "Сайт-визитка дипломата",
		description: "Официальный сайт с поддержкой 3 языков (русский/английский/французский) и строгим дизайном",
		icon: <FaGem />,
		tech: ["ReactJS", "Vite", "i18n", "Мультиязычность"],
		featured: true,
		demo: "https://officialstyle.vercel.app/",
		image: "/images/official.png",
	},
	{
		id: 5,
		title: "Сайт парикмахера",
		description: "Портфолио мастера с онлайн-записью, выбором услуги и расписанием",
		icon: <FaCut />,
		tech: ["ReactJS", "Vite", "Online Booking"],
		demo: "https://hairdresser-portfolio.vercel.app/",
		image: "/images/hairdresser.jpg",
	},
	// {
		// id: 6,
		// title: "Сайт мастера шугаринга",
		// description: "Студия красоты с онлайн-записью, выбором услуг и галереей работ",
		// icon: <FaHandSparkles />,
		// tech: ["ReactJS", "Vite", "Booking System"],
		// demo: "",
		// image: "/images/portfolio/sugaring.jpg",
	// },
	{
		id: 7,
		title: "Студия маникюра",
		description: "Сайт-визитка мастера маникюра с портфолио работ и онлайн-записью",
		icon: <FaPaintBrush />,
		tech: ["ReactJS", "Vite", "Tailwindcss"],
		demo: "https://natalia-vorobeva.github.io/business_card_manicure/",
		image: "/images/manicure.jpg",
	},
	{
		id: 8,
		title: "Карусели и слайдеры",
		description: "Коллекция различных слайдеров для сайтов: Swiper, Embla, Splide, Lightbox",
		icon: <FaHands />,
		tech: ["Swiper", "Embla", "Splide", "Lightbox", "JavaScript"],
		demo: "https://natalia-vorobeva.github.io/carousels/",
		image: "/images/sliders.jpg",
	},
	{
		id: 9,
		title: "Дашборд мировых новостей",
		description: "Визуализация и фильтрация мировых новостей в реальном времени с помощью d3.js",
		icon: <FaGlobeAmericas />,
		tech: ["d3.js", "Data Visualization", "API Integration", "News Aggregation"],
		featured: true,
		demo: "https://d3-news.vercel.app/",
		image: "/images/news-dashboard.jpg",
	},
	{
		id: 10,
		title: "Студия шугаринга",
		description: "Еще один вариант сайта для мастера шугаринга с галереей и онлайн-записью",
		icon: <FaHandSparkles />,
		tech: ["ReactJS", "Vite", "Photo Gallery"],
		demo: "https://natalia-vorobeva.github.io/business_card_sugaring/",
		image: "/images/shugaring.jpg",
	},
];